export const cardData = [
  {
    title: "Plan the perfect New York Vacation",
    stars: 4.99,
    totalRatings: 153,
    location: "United States",
    price: 1564,
    image: "model1.jpg",
  },
  {
    title: "Design your trip to barcelona",
    stars: 5,
    totalRatings: 19,
    location: "Spain",
    price: 3117,
    image: "model2.jpg",
  },
  {
    title: "Craft a custom trip to Korea",
    stars: 4.97,
    totalRatings: 60,
    location: "South Korea",
    price: 3473,
    image: "model3.jpg",
  },
  {
    title: "Live Tulum like a Local",
    stars: 4.63,
    totalRatings: 5,
    location: "Mexico",
    price: 624,
    image: "model4.jpg",
  },
  {
    title: "Plan a trip to amazing Austin",
    stars: 4.75,
    totalRatings: 12,
    location: "United States",
    price: 2058,
    image: "model5.jpg",
  },
  {
    title: "Create your Rome itineary",
    stars: 4.91,
    totalRatings: 43,
    location: "Italy",
    price: 985,
    image: "model6.jpg",
  },
  {
    title: "Plan a Venice venture",
    stars: 5.0,
    totalRatings: 16,
    location: "Italy",
    price: 2461,
    image: "model7.jpg",
  },
  {
    title: "Plan a trip to the Nashville",
    stars: 4.98,
    totalRatings: 41,
    location: "United States",
    price: 988,
    image: "model8.jpg",
  },
  {
    title: "Plan a perfect trip to sunny Miami",
    stars: 5.0,
    totalRatings: 4,
    location: "United States",
    price: 1729,
    image: "model9.jpg",
  },
  {
    title: "From paris with laughs",
    stars: 4.82,
    totalRatings: 120,
    location: "France",
    price: 1149,
    image: "model11.jpg",
  },
  {
    title: "Hike to Mt. Fuji",
    stars: 4.91,
    totalRatings: 50,
    location: "Japan",
    price: 893,
    image: "model10.jpg",
  },
  {
    title: "Get lost in the beauty of India",
    stars: 4.9,
    totalRatings: 90,
    location: "India",
    price: 1256,
    image: "model12.jpg",
  },
];
